name: CI

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} (${{ matrix.dependency-version }})

    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          tools: prestissimo, cs2pr
          coverage: pcov

      - name: Composer Dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: CodeSniffer
        run: vendor/bin/phpcs --report=checkstyle | cs2pr

      - name: PHPStan
        run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0